In [6]:
import numpy as np
from scipy.linalg import circulant

#Affichage des matrices A et C
a = np.array([1, 2, 3, 4, 5])
c = np.array([0, 1, 0, 0, 0])

A = circulant(a)
C = circulant(c)

print("Matrice A :")
print(A)
print("Matrice C :")
print(C)

#Calculons les puissances successives de C afin de vérifier que A = I + SUM(K*C⁽K-1⁾)

I = np.eye(5)
s = np.zeros_like(A)

for k in range(2, 6):
  s += k * np.linalg.matrix_power(C, k-1)

# Vérification de la formule
print("Vérification de la formule :")
print(np.allclose(A, I + s))


# Calcul des valeurs propres et vecteurs propres
lambda_k, X_k = np.linalg.eig(C)

# Vérification des valeurs propres
for k in range(5):
  print(f"Valeur propre {k+1} : {lambda_k[k]}")
  print(f"Valeur attendue : {np.exp(2j*np.pi*k/5)}")
  print("-" * 20)

# Vérification des vecteurs propres
for k in range(5):
  print(f"Vecteur propre {k+1} :")
  print(X_k[:, k])
  print("Vecteur attendu :")
  print(np.array([np.exp(2j*np.pi*k*j/5) for j in range(5)]))
  print("-" * 20)

# Calcul des valeurs propres de A
lambda_A = 1 + np.sum(np.arange(2, 6) * lambda_k**np.arange(2, 6), axis=1)

# Affichage des valeurs propres
print("Valeurs propres de A :")
print(lambda_A)

# Déterminer les vecteurs propres de C
X_C = np.linalg.eig(C)[1]

# Déterminer les vecteurs propres de A
X_A = np.zeros((5, 5), dtype=complex)
for k in range(5):
  X_A[:, k] = X_C[:, k]

# Affichage des vecteurs propres
print("Vecteurs propres de A :")
print(X_A)

# Décomposition spectrale
P = X_A
D = np.diag(lambda_A)

# Vérification
print("Vérification de la décomposition spectrale :")
print(np.allclose(A, np.dot(P, np.dot(D, np.linalg.inv(P))))) #A et PDP-¹


#for K in range(5):
 #   Vp_c = np.linalg.eig(C)
   # L = w^K
   # w = np.exp(2*np.pi*i/5)
    #K=K+1
    #print(np.allclose(w^K, Vp_c))
    
Vp_c = np.linalg.eig(C)
print(Vp_c)

Matrice A :
[[1 5 4 3 2]
 [2 1 5 4 3]
 [3 2 1 5 4]
 [4 3 2 1 5]
 [5 4 3 2 1]]
Matrice C :
[[0 0 0 0 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]
Vérification de la formule :
True
Valeur propre 1 : (-0.809016994374948+0.587785252292473j)
Valeur attendue : (1+0j)
--------------------
Valeur propre 2 : (-0.809016994374948-0.587785252292473j)
Valeur attendue : (0.30901699437494745+0.9510565162951535j)
--------------------
Valeur propre 3 : (0.30901699437494734+0.9510565162951535j)
Valeur attendue : (-0.8090169943749473+0.5877852522924732j)
--------------------
Valeur propre 4 : (0.30901699437494734-0.9510565162951535j)
Valeur attendue : (-0.8090169943749476-0.587785252292473j)
--------------------
Valeur propre 5 : (1+0j)
Valeur attendue : (0.30901699437494723-0.9510565162951536j)
--------------------
Vecteur propre 1 :
[-0.3618034+0.26286556j  0.4472136+0.j         -0.3618034-0.26286556j
  0.1381966+0.4253254j   0.1381966-0.4253254j ]
Vecteur attendu :
[1.+0.j 1.+0.j 1.+0.j 1.+

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [5]:
#exercice 1

import numpy as np
from scipy.linalg import circulant

a = np.array([1, 2, 3, 4, 5])
c = np.array([0, 1, 0, 0, 0])

A = circulant(a)
C = circulant(c)

sum_Ck = np.zeros_like(A)
for k in range(3, 6):
  sum_Ck += k * np.linalg.matrix_power(C, k-1)

print(np.allclose(A, I + sum_Ck))

eigenvalues, eigenvectors = np.linalg.eig(C)

for k in range(5):
  print(f"Eigenvalue {k+1}: {eigenvalues[k]}")
  print(f"Expected value: {np.exp(2j*np.pi*k/5)}")
  print("-" * 20)

for k in range(5):
  print(f"Eigenvector {k+1}:")
  print(eigenvectors[:, k])
  print("Expected vector:")
  print(np.array([np.exp(2j*np.pi*k*j/5) for j in range(5)]))
  print("-" * 20)

eigenvalues_A = 1 + np.sum(np.arange(1, 6) * eigenvalues**np.arange(1, 6), axis=1)

# Print the eigenvalues of A
print("Eigenvalues of A:")
print(eigenvalues_A)

# Calculate the eigenvectors of A
eigenvectors_A = np.linalg.eig(A)[1]

# Print the eigenvectors of A
print("Eigenvectors of A:")
print(eigenvectors_A)

# Calculate the spectral decomposition of A
P = eigenvectors_A
D = np.diag(eigenvalues_A)

# Verify the spectral decomposition
print("Verification of the spectral decomposition:")
print(np.allclose(A, np.dot(P, np.dot(D, np.linalg.inv(P)))))


A = np.array([[10, 7, 8, 7],
              [7, 5, 6, 5],
              [8, 6, 10, 9],
              [7, 5, 9, 10]])

b = np.array([32, 23, 33, 31])

vp = np.linalg.eigvals(A)

if np.all(vp > 0):
    print("La matrice est symétrique définie positive.")
else:
    print("La matrice n'est pas symétrique définie positive.")

#2

def cond_2(A):
    A_conj_tran = np.conjugate(np.transpose(A))  # A*
    A_A = np.dot(A_conj_tran, A)  # A* A    
    vp = np.linalg.eigvals(A_A)
    c = np.max(np.sqrt(np.abs(vp))) / np.min(np.sqrt(np.abs(vp)))    
    return c


if cond_2(A) ==  np.linalg.cond(A):
    print("le conditionnement 2 est verifié")
else:
    print("le conditionnement 2 n'est pas verifié")

#3


# Résoudre le système d'équations linéaires Ax = b
x = np.linalg.solve(A, b)

print("Solution du système d'équations linéaires:")
print(x)


#4

delta_b = np.array([0.1, -0.1, 0.1, -0.1])

y = np.linalg.solve(A, b + delta_b)
print(y)

delta_x = y - x

def comparer(a,b):
    return a == b

norm_delta_b = np.linalg.norm(delta_b)
norm_b = np.linalg.norm(b)

norm_delta_x = np.linalg.norm(delta_x)
norm_x = np.linalg.norm(x)

k1 = comparer(norm_delta_b / norm_b, norm_delta_x / norm_x)
print(k1)


if np.array_equal(np.linalg.eigvals(A_A), np.linalg.eigvals(A)):
    if norm_delta_x / norm_x <= cond_2 *  norm_delta_b / norm_b:
        print("La condition est vérifiée : norm_delta_x / norm_x <= cond_2(A) * norm_delta_b / norm_b")
else:
    print("Les valeurs propres de A_A ne sont pas les mêmes que celles de A.")













NameError: name 'I' is not defined

In [2]:

import numpy as np

A = np.array([[10, 7, 8, 7],
              [7, 5, 6, 5],
              [8, 6, 10, 9],
              [7, 5, 9, 10]])

b = np.array([32, 23, 33, 31])

vp = np.linalg.eigvals(A)

if np.all(vp > 0):
    print("La matrice est symétrique définie positive.")
else:
    print("La matrice n'est pas symétrique définie positive.")

def cond_2(A):
    A_conj_tran = np.conjugate(np.transpose(A))
    A_A = np.dot(A_conj_tran, A)
    vp = np.linalg.eigvals(A_A)
    c = np.max(np.sqrt(np.abs(vp))) / np.min(np.sqrt(np.abs(vp)))
    return c

if cond_2(A) == np.linalg.cond(A):
    print("le conditionnement 2 est verifié")
else:
    print("le conditionnement 2 n'est pas verifié")

x = np.linalg.solve(A, b)
print("Solution du système d'équations linéaires:")
print(x)

delta_b = np.array([0.1, -0.1, 0.1, -0.1])

y = np.linalg.solve(A, b + delta_b)
print(y)

delta_x = y - x

def comparer(a,b):
    return a == b

norm_delta_b = np.linalg.norm(delta_b)
norm_b = np.linalg.norm(b)

norm_delta_x = np.linalg.norm(delta_x)
norm_x = np.linalg.norm(x)

k1 = comparer(norm_delta_b / norm_b, norm_delta_x / norm_x)
print(k1)

if np.array_equal(np.linalg.eigvals(A_A), np.linalg.eigvals(A)):
    if norm_delta_x / norm_x <= cond_2(A) * norm_delta_b / norm_b:
        print("La condition est vérifiée : norm_delta_x / norm_x <= cond_2(A) * norm_delta_b / norm_b")
else:
    print("Les valeurs propres de A_A ne sont pas les mêmes que celles de A.")

#exercice 3

A = np.array( [
    [0, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 1, 0, 0, 0],
    [0, 1, 1, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 1, 1, 0],
    [0, 0, 1, 0, 0, 0, 1, 0, 1],
    [0, 0, 0, 0, 1, 1, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 1, 1, 1, 0]
])

# Affichage de la matrice d'adjacence
for row in A:
    print(row)
A_5 = np.linalg.matrix_power(A, 5)

nombre_trajet = A_5(0,8)
print(nombre_trajet)

import numpy as np

A=np.array([[0,1,1,0,0,0,0,0,0],[1,0,1,1,0,0,0,0,0],[1,1,0,1,0,1,0,0,0],[0,1,1,0,1,0,0,0,0],[0,0,0,1,0,0,1,1,0],[0,0,1,0,0,0,1,0,1],[0,0,0,0,1,1,0,0,1],[0,0,0,0,1,0,0,0,1],[0,0,0,0,0,1,1,1,0]])
np.linalg.matrix_power(A,5)


#Exercice 4
Import numpy as np

d = np.random.random(size=3)
d.sort()
D = np.diagflat(d)
p = [[1,3,3],[1,2,4],[1,4,3]]
Q, R = np.linalg.qr(p)
b = np.linalg.cond(Q)
A = Q @ D @ Q.T
print(A)


vp, vecp = np.linalg.eig(A)

for i in range(len(vp)):
    print("Valeur propre", i+1, ":", vp[i])
    print("Vecteur propre associé :", vecp[:, i])

epsilon = 1e-6
delta_b = epsilon * Q[:, 0]
b = Q[:, -1]
x = np.linalg.solve(A, b)
delta_x = np.linalg.solve(A, delta_b)
print(x)
print(delta_x)



SyntaxError: invalid syntax (2197980834.py, line 85)