In [17]:
import numpy as np

A=np.array([[0,1,1,0,0,0,0,0,0],[1,0,1,1,0,0,0,0,0],[1,1,0,1,0,1,0,0,0],[0,1,1,0,1,0,0,0,0],[0,0,0,1,0,0,1,1,0],[0,0,1,0,0,0,1,0,1],[0,0,0,0,1,1,0,0,1],[0,0,0,0,1,0,0,0,1],[0,0,0,0,0,1,1,1,0]])
np.linalg.matrix_power(A,5)

array([[20, 34, 42, 23, 20, 16, 13,  5, 15],
       [34, 38, 47, 43, 17, 26, 23, 14, 15],
       [42, 47, 46, 53, 24, 44, 28, 21, 19],
       [23, 43, 53, 26, 36, 25, 17,  6, 29],
       [20, 17, 24, 36,  8, 29, 39, 30, 14],
       [16, 26, 44, 25, 29, 26, 34, 18, 34],
       [13, 23, 28, 17, 39, 34, 22, 12, 39],
       [ 5, 14, 21,  6, 30, 18, 12,  4, 30],
       [15, 15, 19, 29, 14, 34, 39, 30, 20]])

### ouais il a 15 chemins possible

### Exercice 4:

In [39]:
a=np.random.random(size=3)
np.sort(a)
print(a)

[0.35493754 0.98085272 0.88255112]


In [40]:
D=np.diagflat(a)
print(D)

[[0.35493754 0.         0.        ]
 [0.         0.98085272 0.        ]
 [0.         0.         0.88255112]]


In [41]:
P=[[1,2,3],[1,2,4],[1,4,5]]
np.linalg.inv(P)

array([[ 3. , -1. , -1. ],
       [ 0.5, -1. ,  0.5],
       [-1. ,  1. ,  0. ]])

In [42]:
Q,R=np.linalg.qr(P)
print(Q,R)

[[-5.77350269e-01 -4.08248290e-01 -7.07106781e-01]
 [-5.77350269e-01 -4.08248290e-01  7.07106781e-01]
 [-5.77350269e-01  8.16496581e-01 -2.25745422e-16]] [[-1.73205081 -4.61880215 -6.92820323]
 [ 0.          1.63299316  1.22474487]
 [ 0.          0.          0.70710678]]


In [43]:
Q1=Q.dot(D)
A=Q1.dot(Q.T)
print(A)

[[ 0.72306352 -0.15948759 -0.20863839]
 [-0.15948759  0.72306352 -0.20863839]
 [-0.20863839 -0.20863839  0.77221433]]


In [53]:
b=Q[:,2]
x=np.linalg.solve(A,b)
print(x)

[-8.01207736e-01  8.01207736e-01 -1.24600680e-16]


In [52]:
print((1/a[2])*b)

[-8.01207736e-01  8.01207736e-01 -2.55787363e-16]


In [56]:
ep=8
db=ep*Q[:,0]
dx=np.linalg.solve(A,db)
print(dx)

[-13.01299977 -13.01299977 -13.01299977]


In [57]:
print((1/a[0])*db)

[-13.01299977 -13.01299977 -13.01299977]


In [62]:
print(np.linalg.cond(A)*(np.linalg.norm(db)/np.linalg.norm(b)))

22.107612766258523


In [63]:
print((np.linalg.norm(dx)/np.linalg.norm(x)))

19.891975583073275


### Pourquoi c'est pas la meme chose