In [49]:
### import numpy as np
import math
import scipy.linalg
import scipy.stats as spi
import matplotlib.pyplot as plt

#Qst 1
def Laplacien_dirichelet(N):
    h = 1/(N+1)
    Ah = 1/h**2 * (2 * np.eye(N) - np.eye(N, k=1) - np.eye(N, k=-1))

    return Ah
N = 10
Ah = Laplacien_dirichelet(N)
print(Ah)


#qst2
l = np.linalg.eig(Ah)
print (l)

#if all(l > 0):
    
#    print("La matrice est définie positive.")

#Qst3   
def eigval_exact (N):
    h = 1/(N+1)
    for k in range(1, N):
        eigval = (2 / h ** 2) * (1 - np.cos(k * np.pi * h))

    return eigval

#Qst4
Val_exact = eigval_exact (N)
print (Val_exact)


#Qst5
def power_method (A, Nit, x0 ):
    x = x0 / np.linalg.norm(x0)
    for k in range(1, Nit):
        x = np.dot(A, x)
        x = x / np.linalg.norm(x)
        lmbda = np.dot (x.T , np.dot(A, x))
    return lmbda, x

#Qst6
x0 = np.random.rand(N)
A = power_method ( Ah,𝑁 ,𝑥0 )
print (A)
#comparer 1er méthode
#sont_proches = np.allclose(np.linalg.eig(Ah), Val_exact)

#if sont_proches:
#    print("Les valeurs propres calculées sont proches des valeurs exactes.")
#else:
#    print("Les valeurs propres calculées ne correspondent pas aux valeurs exactes.")
    
#comparer 2eme méthode

tolerance = 0.0001
eigval = np.linalg.eig(Ah)
sont_proches = np.all(np.abs(eigval - Val_exact) < tolerance)
if sont_proches : 
    print ("Les valeurs propres sont proches")
else:
    print ("Les valeurs propres sont différentes")
    
# La valeur propre calculée est 445.5833549451458
# L'influence du nombre d'itération Nit 


#Qst7

def orthonormalize (X):
    Q = np.linalg.qr(Ah)
return Q

X = np.random.rand(N)
QR = orthonormalize (X)


#Qst8

def power_method_orth (A, Nit, X0):
    X = orthonormalize (X0)
    for k in range(1, Nit):
        x = np.dot(A, x)
        X = orthonormalize (X)
        lmbda = np.dot(X.T , np.dot(A,X))
return np.diag(lmbda,X)

#Qst9

P = power_method_orth(Ah, 10, X0)
print(P)
#vérifier qu’elle permet de calculer les 𝑃 plus grandes valeurs propres

#Qst10

# X0 = 1 power_method_orth() = la méthode QR
#elle permet de trouver toutes les valeurs propres de 𝐴ℎ

[[ 242. -121.    0.    0.    0.    0.    0.    0.    0.    0.]
 [-121.  242. -121.    0.    0.    0.    0.    0.    0.    0.]
 [   0. -121.  242. -121.    0.    0.    0.    0.    0.    0.]
 [   0.    0. -121.  242. -121.    0.    0.    0.    0.    0.]
 [   0.    0.    0. -121.  242. -121.    0.    0.    0.    0.]
 [   0.    0.    0.    0. -121.  242. -121.    0.    0.    0.]
 [   0.    0.    0.    0.    0. -121.  242. -121.    0.    0.]
 [   0.    0.    0.    0.    0.    0. -121.  242. -121.    0.]
 [   0.    0.    0.    0.    0.    0.    0. -121.  242. -121.]
 [   0.    0.    0.    0.    0.    0.    0.    0. -121.  242.]]
(array([474.19729961, 445.58335495, 400.47629761, 342.53043315,
       276.44019086, 207.55980914,   9.80270039,  38.41664505,
        83.52370239, 141.46956685]), array([[ 0.12013117,  0.23053002,  0.3222527 ,  0.38786839, -0.42206128,
         0.42206128, -0.12013117,  0.23053002, -0.3222527 , -0.38786839],
       [-0.23053002, -0.38786839, -0.42206128, -0.3222527 

/tmp/ipykernel_5678/1730680560.py:64: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  sont_proches = np.all(np.abs(eigval - Val_exact) < tolerance)


ValueError: could not broadcast input array from shape (10,10) into shape (10,)

In [48]:
import math
import scipy.linalg
import scipy.stats as spi
import matplotlib.pyplot as plt


# Exercice 2
# Question 1




Matrice du Laplacien :
[[ 242. -121.    0.    0.    0.    0.    0.    0.    0.    0.]
 [-121.  242. -121.    0.    0.    0.    0.    0.    0.    0.]
 [   0. -121.  242. -121.    0.    0.    0.    0.    0.    0.]
 [   0.    0. -121.  242. -121.    0.    0.    0.    0.    0.]
 [   0.    0.    0. -121.  242. -121.    0.    0.    0.    0.]
 [   0.    0.    0.    0. -121.  242. -121.    0.    0.    0.]
 [   0.    0.    0.    0.    0. -121.  242. -121.    0.    0.]
 [   0.    0.    0.    0.    0.    0. -121.  242. -121.    0.]
 [   0.    0.    0.    0.    0.    0.    0. -121.  242. -121.]
 [   0.    0.    0.    0.    0.    0.    0.    0. -121.  242.]]
Valeurs propres calculées : [474.19729961 445.58335495 400.47629761 342.53043315 276.44019086
 207.55980914   9.80270039  38.41664505  83.52370239 141.46956685]
Valeurs propres exactes : [9.802700385291637, 38.41664505485415, 83.52370238524104, 141.46956685354348, 207.55980913786502, 276.440190862135, 342.5304331464565, 400.47629761475895, 445.